### ISSUE TITLE
op hotkey not working

### ISSUE THREAD

**Issue by mwd102** [KairuDeibisu/PowerToysRunPlugin1Password#7]
Plugin is installed as directed, when the op keyword is entered the powertoys run box does not show any lastpass related info. I am a multi acct user, if I do not specify an acct, i do see a notice when i type Op that i must specify and email but when the email is provided it then shows nothing. Email is blank in screenshot for privacy.

I've tried with most settings enabled and the minimal settings. Powertoys v.0.83.0, plugin latest x64 release

![image](https://github.com/user-attachments/assets/31eed0cd-9496-45d8-93cb-aa290100c867)

**Comment by KairuDeibisu** [comment]
Can you provide logs from C:\Users\[YOU USER]\AppData\Local\Microsoft\PowerToys1PasswordPluginLogs\

Please try https://github.com/KairuDeibisu/PowerToysRunPlugin1Password/releases/tag/v1.4.1

I've updated the libs for power toys.

**Comment by KairuDeibisu** [comment]
May be releated to #8
